[package]
name = "solana_libra_storage_client"
version = "0.0.1-sol"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra storage client"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = { version = "=0.3.0-alpha.19", package = "futures-preview", features = ["compat"] }
futures_01 = { version = "0.1.28", package = "futures" }
grpcio = { version = "=0.5.0-alpha.4", default-features = false, features = ["prost-codec"] }
rand = "0.6.5"
solana-libra-crypto = { path = "../../crypto/crypto", version = "0.0.1-sol" }
failure = { path = "../../common/failure_ext", version = "0.0.1-sol", package = "solana_libra_failure_ext" }
solana-libra-metrics = { path = "../../common/metrics", version = "0.0.1-sol" }
solana-libra-scratchpad = { path = "../scratchpad", version = "0.0.1-sol" }
solana_libra_state_view = { path = "../state_view", version = "0.0.1-sol" }
solana_libra_storage_proto = { path = "../storage_proto", version = "0.0.1-sol" }
solana-libra-types = { path = "../../types", version = "0.0.1-sol" }

[dev-dependencies]
solana-libra-types = { path = "../../types", version = "0.0.1-sol", features = ["testing"] }
