[package]
name = "solana_libra_storage_proto"
version = "0.0.1-sol4"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra storage proto"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bytes = "0.4.12"
futures = "0.1.28"
grpcio = { version = "=0.5.0-alpha.4", default-features = false, features = ["prost-codec"] }
proptest = "0.9.2"
proptest-derive = "0.1.0"
prost = "0.5.0"

solana_libra_crypto = { path = "../../crypto/crypto", version = "0.0.1-sol4" }
failure = { path = "../../common/failure_ext", version = "0.0.1-sol4", package = "solana_libra_failure_ext" }
solana_libra_types = { path = "../../types", version = "0.0.1-sol4" }

[build-dependencies]
grpcio-compiler = { version = "0.5.0-alpha.2", default-features = false, features = ["prost-codec"] }

[dev-dependencies]
solana_libra_types = { path = "../../types", version = "0.0.1-sol4", features = ["testing"]}
solana_libra_prost_ext = { path = "../../common/prost-ext", version = "0.0.1-sol4" }
