[package]
name = "solana-libra-config-builder"
version = "0.0.1-sol"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra config builder"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
hex = { version = "0.3.2", default-features = false }
parity-multiaddr = { version = "0.5.0", default-features = false }
rand = "0.6.5"
structopt = "0.3.2"

solana-libra-config = { path = "..", version = "0.0.1-sol" }
solana-libra-crypto = { path = "../../crypto/crypto", version = "0.0.1-sol" }
failure = { path = "../../common/failure_ext", version = "0.0.1-sol", package = "solana_libra_failure_ext" }
solana-libra-generate-keypair = { path = "../generate-keypair", version = "0.0.1-sol" }
solana-libra-logger = { path = "../../common/logger", version = "0.0.1-sol" }
solana-libra-prost-ext = { path = "../../common/prost-ext", version = "0.0.1-sol" }
solana-libra-types = { path = "../../types", version = "0.0.1-sol" }
solana_libra_vm_genesis = { path = "../../language/vm/vm_genesis", version = "0.0.1-sol" }

[dev-dependencies]
solana-libra-types = { path = "../../types", version = "0.0.1-sol", features = ["testing"]}
