[package]
name = "solana_libra_invalid_mutations"
version = "0.0.1-sol2"
edition = "2018"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra invalid mutations"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false

[dependencies]
proptest = "0.9"
solana_libra_proptest_helpers = { path = "../../../common/proptest_helpers", version = "0.0.1-sol2" }
solana-libra-vm = { path = "../../vm", version = "0.0.1-sol2" }
solana-libra-types = { path = "../../../types", version = "0.0.1-sol2" }

[dev-dependencies]
solana-libra-vm = { path = "../../vm", version = "0.0.1-sol2", features = ["testing"] }
