[package]
name = "solana-libra-vm"
version = "0.0.1-sol"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra vm"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
byteorder = "1.3.2"
hex = "0.3.2"
lazy_static = "1.3.0"
mirai-annotations = "1.4.0"
proptest = "0.9"
proptest-derive = "0.1.1"
serde = { version = "1", features = ["derive"] }
solana_libra_canonical_serialization = { path = "../../common/canonical_serialization", version = "0.0.1-sol" }
solana-libra-crypto = { path = "../../crypto/crypto", version = "0.0.1-sol" }
failure = { path = "../../common/failure_ext", version = "0.0.1-sol", package = "solana_libra_failure_ext" }
solana_libra_proptest_helpers = { path = "../../common/proptest_helpers", version = "0.0.1-sol" }
solana-libra-types = { path = "../../types", version = "0.0.1-sol" }

[dev-dependencies]
serde_json = "1"
solana-libra-types = { path = "../../types", version = "0.0.1-sol", features = ["testing"]}

[features]
default = []
mirai-contracts = []
testing = ["solana-libra-types/testing"]
