[package]
name = "solana_libra_functional_tests"
version = "0.0.1-sol"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra functional tests"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
failure = { path = "../../common/failure_ext", version = "0.0.1-sol", package = "solana_libra_failure_ext" }
solana_libra_ir_to_bytecode_syntax = { path = "../compiler/ir_to_bytecode/syntax", version = "0.0.1-sol" }
solana_libra_ir_to_bytecode = { path = "../compiler/ir_to_bytecode", version = "0.0.1-sol" }
solana-libra-stdlib = { path = "../stdlib", version = "0.0.1-sol" }
solana-libra-types = { path = "../../types", version = "0.0.1-sol" }
solana-libra-vm = { path = "../vm", version = "0.0.1-sol" }
solana_libra_bytecode_verifier = { path = "../bytecode_verifier", version = "0.0.1-sol" }
solana_libra_language_e2e_tests = { path = "../e2e_tests", version = "0.0.1-sol" }
solana-libra-config = { path = "../../config", version = "0.0.1-sol" }
filecheck = "0.4.0"
lazy_static = "1.3.0"
regex = { version = "1.3.0", default-features = false, features = ["std", "perf"] }

[dev-dependencies]
solana-libra-types = { path = "../../types", version = "0.0.1-sol", features = ["testing"] }
solana-libra-datatest-stable = { path = "../../common/datatest-stable", version = "0.0.1-sol" }

[[test]]
name = "testsuite"
harness = false
