[package]
name = "solana-libra-scratchpad"
version = "0.0.1-sol4"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra scratchpad"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
itertools = "0.8.0"

solana_libra_crypto = { path = "../../crypto/crypto", version = "0.0.1-sol4" }
solana_libra_types = { path = "../../types", version = "0.0.1-sol4" }

[dev-dependencies]
proptest = "0.9.4"

solana_libra_types = { path = "../../types", version = "0.0.1-sol4", features = ["testing"] }
