[package]
name = "solana_libra_bytecode_verifier"
version = "0.0.1-sol4"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra bytecode verifier"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
edition = "2018"

[dependencies]
mirai-annotations = "1.4.0"
petgraph = "0.4"

failure = { path = "../../common/failure_ext", version = "0.0.1-sol4", package = "solana_libra_failure_ext" }
solana_libra_vm = { path = "../vm", version = "0.0.1-sol4" }
solana_libra_types = { path = "../../types", version = "0.0.1-sol4" }
solana_libra_vm_runtime_types = { path = "../vm/vm_runtime/vm_runtime_types", version = "0.0.1-sol4" }


[dev-dependencies]
solana_libra_invalid_mutations = { path = "invalid_mutations", version = "0.0.1-sol4" }
solana_libra_types = { path = "../../types", version = "0.0.1-sol4", features = ["testing"]}
solana_libra_vm = { path = "../vm", version = "0.0.1-sol4", features = ["testing"]}

[features]
default = []
testing = ["solana_libra_vm/testing", "solana_libra_types/testing"]
