[package]
name = "solana-libra-executor"
version = "0.0.1-sol2"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra executor"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
backoff = { version = "0.1.5", default-features = false }
solana-libra-config-builder = { path = "../../config/config-builder", version = "0.0.1-sol2" }
futures = { version = "=0.3.0-alpha.19", package = "futures-preview" }
itertools = { version = "0.8.0", default-features = false }
lazy_static = { version = "1.3.0", default-features = false }
rusty-fork = { version = "0.2.2", default-features = false }
serde = { version = "1.0.99", default-features = false }

solana_libra_canonical_serialization = { path = "../../common/canonical_serialization", version = "0.0.1-sol2" }
solana-libra-config = { path = "../../config", version = "0.0.1-sol2" }
solana-libra-crypto = { path = "../../crypto/crypto", version = "0.0.1-sol2" }
failure = { path = "../../common/failure_ext", version = "0.0.1-sol2", package = "solana_libra_failure_ext" }
solana-libra-logger = { path = "../../common/logger", version = "0.0.1-sol2" }
solana-libra-metrics = { path = "../../common/metrics", version = "0.0.1-sol2" }
solana-libra-prost-ext = { path = "../../common/prost-ext", version = "0.0.1-sol2" }
solana-libra-scratchpad = { path = "../../storage/scratchpad", version = "0.0.1-sol2" }
solana_libra_state_view = { path = "../../storage/state_view", version = "0.0.1-sol2" }
solana_libra_storage_client = { path = "../../storage/storage_client", version = "0.0.1-sol2" }
solana-libra-types = { path = "../../types", version = "0.0.1-sol2" }
solana_libra_vm_runtime = { path = "../../language/vm/vm_runtime", version = "0.0.1-sol2" }

[dev-dependencies]
grpcio = { version = "=0.5.0-alpha.4", default-features = false }
proptest = "0.9.2"
rand = "0.6.5"
rusty-fork = "0.2.1"

solana-libra-config = { path = "../../config", version = "0.0.1-sol2", features = ["testing"]}
solana_libra_grpc_helpers = { path = "../../common/grpc_helpers", version = "0.0.1-sol2" }
solana-libra-types = { path = "../../types", version = "0.0.1-sol2", features = ["testing"]}

solana_libra_storage_proto = { path = "../../storage/storage_proto", version = "0.0.1-sol2" }
solana-libra-storage-service = { path = "../../storage/storage-service", version = "0.0.1-sol2" }
solana_libra_vm_genesis = { path = "../../language/vm/vm_genesis", version = "0.0.1-sol2" }
solana_libra_transaction_builder = { path = "../../language/transaction_builder", version = "0.0.1-sol2" }
