[package]
name = "solana_libra_language_e2e_tests"
version = "0.0.1-sol"
edition = "2018"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra language e2e tests"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false

[dependencies]
solana_libra_bytecode_verifier = { path = "../bytecode_verifier", version = "0.0.1-sol" }
solana_libra_canonical_serialization = { path = "../../common/canonical_serialization", version = "0.0.1-sol" }
failure = { path = "../../common/failure_ext", version = "0.0.1-sol", package = "solana_libra_failure_ext" }
solana-libra-compiler = { path = "../compiler", version = "0.0.1-sol" }
lazy_static = "1.3.0"
solana-libra-crypto = { path = "../../crypto/crypto", version = "0.0.1-sol"}
rand = "0.6.5"
solana_libra_state_view = { path = "../../storage/state_view", version = "0.0.1-sol" }
solana-libra-types = { path = "../../types", version = "0.0.1-sol" }
solana_libra_transaction_builder = { path = "../transaction_builder", version = "0.0.1-sol", features = ["testing"]}
solana-libra-vm = { path = "../vm", version = "0.0.1-sol" }
solana_libra_vm_genesis = { path = "../vm/vm_genesis", version = "0.0.1-sol" }
solana_libra_vm_runtime = { path = "../vm/vm_runtime", version = "0.0.1-sol" }
solana_libra_vm_runtime_types = { path = "../vm/vm_runtime/vm_runtime_types", version = "0.0.1-sol" }
proptest = "0.9.3"
proptest-derive = "0.1.1"
solana_libra_proptest_helpers = { path = "../../common/proptest_helpers", version = "0.0.1-sol" }
prost = "0.5.0"
solana-libra-config =  { path = "../../config", version = "0.0.1-sol" }
solana-libra-logger = { path = "../../common/logger", version = "0.0.1-sol" }
solana-libra-stdlib = { path = "../stdlib", version = "0.0.1-sol" }
walkdir = "2.2.9"

[dev-dependencies]
solana-libra-types = { path = "../../types", version = "0.0.1-sol", features = ["testing"] }
