[package]
name = "solana-libra-libradb"
version = "0.0.1-sol3"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra libradb"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
arc-swap = "0.4.2"
byteorder = "1.3.2"
itertools = "0.8.0"
lazy_static = "1.2.0"
num-derive = "0.2"
num-traits = "0.2"
proptest = "0.9.2"
proptest-derive = "0.1.2"
prost = "0.5.0"
rand = "0.6.5"
rusty-fork = "0.2.1"
strum = "0.15.0"
strum_macros = "0.15.0"

solana-libra-accumulator = { path = "../accumulator", version = "0.0.1-sol3" }
solana_libra_canonical_serialization = { path = "../../common/canonical_serialization", version = "0.0.1-sol3" }
solana_libra_crypto = { path = "../../crypto/crypto", version = "0.0.1-sol3" }
failure = { path = "../../common/failure_ext", version = "0.0.1-sol3", package = "solana_libra_failure_ext" }
solana_libra_jellyfish_merkle = { path = "../jellyfish_merkle", version = "0.0.1-sol3" }
solana_libra_logger = { path = "../../common/logger", version = "0.0.1-sol3" }
solana_libra_metrics = { path = "../../common/metrics", version = "0.0.1-sol3" }
solana_libra_prost_ext = { path = "../../common/prost-ext", version = "0.0.1-sol3" }
solana-libra-schemadb = { path = "../schemadb", version = "0.0.1-sol3" }
solana_libra_storage_proto = { path = "../storage_proto", version = "0.0.1-sol3" }
solana_libra_tools = { path = "../../common/tools", version = "0.0.1-sol3" }
solana_libra_types = { path = "../../types", version = "0.0.1-sol3" }

[dev-dependencies]
solana_libra_proptest_helpers = { path = "../../common/proptest_helpers", version = "0.0.1-sol3" }
solana_libra_types = { path = "../../types", version = "0.0.1-sol3", features = ["testing"]}

[features]
default = []
testing = ["solana_libra_types/testing"]
