[package]
name = "solana-libra-generate-keypair"
version = "0.0.1-sol"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra generate keypair"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bincode = { version = "1.1.4", default-features = false }
structopt = "0.3.2"

failure = { path = "../../common/failure_ext", version = "0.0.1-sol", package = "solana_libra_failure_ext" }
solana-libra-crypto = { path = "../../crypto/crypto/", version = "0.0.1-sol"}
solana-libra-tools = { path = "../../common/tools", version = "0.0.1-sol" }
